import { rm } from 'node:fs/promises';

import chalk from 'chalk';
import { command } from 'cleye';

import { ConsoleManager } from '../managers/console.manager.js';
import { AICOMMIT_LOGS_DIR } from '../utils/config.js';
import { KnownError, handleCliError } from '../utils/error.js';

export default command(
    {
        name: 'log',
        parameters: ['<removeAll>'],
        help: {
            description: 'Manage log files generated by the application',
            examples: ['aic2 log removeAll'],
        },
    },
    argv => {
        (async () => {
            const { removeAll } = argv._;

            if (removeAll === 'removeAll') {
                await rm(AICOMMIT_LOGS_DIR, { recursive: true, force: true });
                console.log(`${chalk.green('✔')} All Log files are removed!`);
                return;
            }

            throw new KnownError(`Invalid mode: ${removeAll}`);
        })().catch(error => {
            const commandLineManager = new ConsoleManager();
            commandLineManager.printError(error.message);
            handleCliError(error);
            process.exit(1);
        });
    }
);
