import fs from 'fs/promises';
import path from 'path';

import { filter, lastValueFrom, map, toArray } from 'rxjs';

import { getAvailableAIs } from './get-available-ais.js';
import { AIRequestManager } from '../managers/ai-request.manager.js';
import { ConsoleManager } from '../managers/console.manager.js';
import { RawConfig, getConfig } from '../utils/config.js';
import { KnownError, handleCliError } from '../utils/error.js';
import { initializeLogger, logger } from '../utils/logger.js';
import { parseHookPositionalArgs } from '../utils/parse-hook-args.js';
import { getBranchName, getRecentCommits, getStagedDiff } from '../utils/vcs.js';

const [messageFilePath, commitSource] = parseHookPositionalArgs(process.argv.slice(2), ['--pre-commit']);

export default (
    locale: string | undefined,
    generate: number | undefined,
    excludeFiles: string[],
    commitType: string | undefined,
    prompt: string | undefined,
    includeBody: boolean | undefined,
    verbose: boolean
) =>
    (async () => {
        if (!messageFilePath) {
            throw new KnownError('Commit message file path is missing. This file should be called from the "pre-commit framework"');
        }

        // If a commit message is passed in, ignore
        if (commitSource) {
            console.log(`Skipping aicommit2 message generation for ${commitSource} commit`);
            return;
        }

        const configOverrides: RawConfig = {
            ...(locale && { locale }),
            ...(generate != null && { generate: generate.toString() }),
            ...(commitType && { type: commitType }),
            ...(prompt && { systemPrompt: prompt }),
            ...(includeBody === true && { includeBody: 'true' }),
        };

        if (verbose) {
            configOverrides.logLevel = 'verbose';
        }

        const config = await getConfig(configOverrides);
        await initializeLogger(config);
        logger.verbose(`[pre-commit] type=${config.type}, systemPrompt=${config.systemPrompt ? 'set' : 'empty'}`);
        if (config.systemPromptPath) {
            try {
                await fs.readFile(path.resolve(config.systemPromptPath), 'utf-8');
            } catch (error) {
                throw new KnownError(`Error reading system prompt file: ${config.systemPromptPath}`);
            }
        }

        // All staged files can be ignored by our filter
        const staged = await getStagedDiff(excludeFiles, config.exclude);
        if (!staged) {
            return;
        }

        const consoleManager = new ConsoleManager();
        consoleManager.printTitle();

        const availableAIs = getAvailableAIs(config, 'commit');
        const hasNoAvailableAIs = availableAIs.length === 0;
        if (hasNoAvailableAIs) {
            throw new KnownError('Please set at least one API key via the `aicommit2 config set` command');
        }

        const branchName = await getBranchName();
        const recentCommits = await getRecentCommits();
        const aiRequestManager = new AIRequestManager(config, staged, branchName, recentCommits);
        let messages: string[];
        try {
            messages = await lastValueFrom(
                aiRequestManager.createCommitMsgRequests$(availableAIs).pipe(
                    filter(data => !data.isError),
                    map(data => data.value),
                    toArray()
                )
            );
        } finally {
            consoleManager.printAnalyzed();
        }

        /**
         * When `--no-edit` is passed in, the base commit message is empty,
         * and even when you use pass in comments via #, they are ignored.
         *
         * Note: `--no-edit` cannot be detected in argvs so this is the only way to check
         */
        const baseMessage = await fs.readFile(messageFilePath, 'utf8');
        const supportsComments = baseMessage !== '';
        const hasMultipleMessages = messages.length > 1;

        let instructions = '';

        if (supportsComments) {
            instructions = '# 🤖 Generated by aicommit2 (https://github.com/tak-bro/aicommit2)\n';
            instructions += '# ----------------------------------------\n';
            instructions += '# How to use:\n';
            if (hasMultipleMessages) {
                instructions += '# 1. Remove the "#" from your chosen message\n';
                instructions += '# 2. Edit the message if needed\n';
                instructions += '# 3. Save and close the editor\n';
            } else {
                instructions += '# 1. The message below will be used\n';
                instructions += '# 2. Edit the message if needed\n';
                instructions += '# 3. Save and close the editor\n';
            }
            instructions += '# ----------------------------------------\n';
        }

        if (hasMultipleMessages) {
            if (supportsComments) {
                instructions += '\n# 📝 Choose one of these messages:\n';
            }
            instructions += `\n${messages.map(message => `# ${message}`).join('\n')}`;
        } else {
            if (supportsComments) {
                instructions += '\n# 📝 Generated commit message:\n';
            }
            instructions += `\n${messages[0]}\n`;
        }

        const currentContent = await fs.readFile(messageFilePath, 'utf8');
        const newContent = instructions + '\n' + currentContent;

        await fs.writeFile(messageFilePath, newContent);
        consoleManager.printSavedCommitMessage();
    })().catch(error => {
        const commandLineManager = new ConsoleManager();
        commandLineManager.printError(error.message);
        handleCliError(error);
        process.exit(1);
    });
